---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	append_system_prompt(append_system_prompt)
	refine_problem_statement(refine_problem_statement)
	tools_1(tools_1)
	parse_queries_add_plan_prompt(parse_queries_add_plan_prompt)
	plan_literature_review(plan_literature_review)
	tools_2(tools_2)
	reflect_on_papers(reflect_on_papers)
	parse_plan(parse_plan)
	__end__([<p>__end__</p>]):::last
	__start__ --> append_system_prompt;
	append_system_prompt --> refine_problem_statement;
	parse_queries_add_plan_prompt --> plan_literature_review;
	plan_literature_review -. &nbsp;__end__&nbsp; .-> parse_plan;
	plan_literature_review -. &nbsp;tools&nbsp; .-> tools_2;
	refine_problem_statement -. &nbsp;__end__&nbsp; .-> parse_queries_add_plan_prompt;
	refine_problem_statement -. &nbsp;tools&nbsp; .-> tools_1;
	reflect_on_papers --> plan_literature_review;
	tools_1 --> refine_problem_statement;
	tools_2 --> reflect_on_papers;
	parse_plan --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
