---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	initialise_refinement_progress(initialise_refinement_progress)
	prepare_subsection_context(prepare_subsection_context)
	write_subsection(write_subsection)
	review_content(review_content)
	process_content_feedback(process_content_feedback)
	review_grounding(review_grounding)
	process_grounding_feedback(process_grounding_feedback)
	advance_to_next(advance_to_next)
	complete_refinement(complete_refinement)
	cleanup_temp_cache(cleanup_temp_cache)
	__end__([<p>__end__</p>]):::last
	__start__ --> initialise_refinement_progress;
	advance_to_next -. &nbsp;complete&nbsp; .-> complete_refinement;
	advance_to_next -. &nbsp;continue&nbsp; .-> prepare_subsection_context;
	complete_refinement --> cleanup_temp_cache;
	initialise_refinement_progress --> prepare_subsection_context;
	prepare_subsection_context --> write_subsection;
	process_content_feedback -. &nbsp;passed&nbsp; .-> advance_to_next;
	process_content_feedback -. &nbsp;retry&nbsp; .-> review_content;
	process_grounding_feedback -. &nbsp;passed&nbsp; .-> review_content;
	process_grounding_feedback -. &nbsp;retry&nbsp; .-> review_grounding;
	review_content --> process_content_feedback;
	review_grounding --> process_grounding_feedback;
	write_subsection --> review_grounding;
	cleanup_temp_cache --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
